# Generated by Django 3.0.5 on 2020-06-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_instrument_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='year',
        ),
    ]
