# Generated by Django 3.0.5 on 2020-06-22 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_instrument_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, 'Year must be greater than 1900'), django.core.validators.MaxValueValidator(2025, 'Year must be less than 2025')], verbose_name='Manufactur year (YYYY)'),
        ),
    ]
