# Generated by Django 3.0.5 on 2020-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200622_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='accessory_type',
            field=models.CharField(default='Amplifier', max_length=150),
            preserve_default=False,
        ),
    ]
