# Generated by Django 3.0.5 on 2020-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_accessory_accessory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='owned',
            field=models.BooleanField(default=True, verbose_name='Do you own this accessory?'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='owned',
            field=models.BooleanField(default=True, verbose_name='Do you own this instrument?'),
        ),
    ]
