# Generated by Django 3.0.5 on 2020-06-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200622_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Accessory')),
            ],
        ),
    ]
