# Generated by Django 3.0.5 on 2020-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_accessoryphoto_instrumentphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoryphoto',
            old_name='accessories',
            new_name='accessory',
        ),
        migrations.RenameField(
            model_name='instrumentphoto',
            old_name='instruments',
            new_name='instrument',
        ),
    ]
