# Generated by Django 3.0.5 on 2020-06-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200623_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='price',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
